name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  FORCE_COLOR: 3
  BCD_DIR: ./browser-compat-data

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Linux
            runs-on: ubuntu-latest
          # - name: macOS
          #   runs-on: macos-latest
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Clone collector
        uses: actions/checkout@v3
      - name: Clone browser-compat-data
        uses: actions/checkout@v3
        with:
          repository: mdn/browser-compat-data
          path: browser-compat-data
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare browser-compat-data
        run: npm ci
        working-directory: browser-compat-data
      - run: npm ci
      - run: npm run format
      - run: npm run build
      - run: npm run unittest
      # ensure we can start the server without dev dependencies
      - name: Production smoke test
        # XXX SWC 1.3.44 is specified due to a bug in 1.3.45; remove version number
        # once https://github.com/swc-project/swc/issues/7203 is resolved
        run: |
          npm i -g ts-node @swc/core@1.3.44
          npm ci --production
          npm start &
          npx wait-on -t 10000 -v http://localhost:8080
        env:
          NODE_ENV: production
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
